### ISSUE TITLE
Add overflow support

### ISSUE THREAD

**Issue by Airkro** [jonathantneal/postcss-short#12]
what about use [PostCSS Overflow](https://github.com/Airkro/postcss-overflow) ?

**Comment by jonathantneal** [comment]
I like this. A few things:

1. Could you get it to run PostCSS 6?
2. Could you patch up this unnecessary clone? https://github.com/Airkro/postcss-overflow/blob/master/index.js#L7-L8

**Comment by Airkro** [comment]
Thanks, I released postcss-overflow 1.1.5

Unnecessary code has been removed.
Now it's working fine in Test Suite with PostCSS 6

**Comment by jonathantneal** [comment]
Soon: https://github.com/jonathantneal/postcss-short/commit/34dd5e5d27c35de14368d3b485bff2ff67a1bb40

**Comment by jonathantneal** [comment]
Published! https://www.npmjs.com/package/postcss-short
