### ISSUE TITLE
/ is the worst thing ever, please stop

### ISSUE THREAD

**Issue by Yzrsah** [jonathantneal/postcss-short#19]
In JSX and CSS in JS, and CSS in Dart, I use math function and computations inside CSS

Mixing the new '/' syntax with math expressions is horrid.

Some thoughtless people are trying to ruin CSS by making `10.0 / 2` have a bizarre new contextual meaning that does not mix in with the functional syntax, or the language syntax, or with any of the design of any of the languages we work with, or with any math expressions or calculations. It will be the source of annoyance and errors forever, like the original JS bugs of the 1990's

It's really thoughtless and lacking insight.

**Comment by jonathantneal** [comment]
Please be aware that `/` is the character used to separate real, shipped values in CSS.

Some of these properties include `grid-column`, `background`, and the `font` declaration.

If you feel this strongly about it, I recommend you avoid styling any layout, color, or text in your CSS, lest you’re forced to encounter these web standards.

Before you call others thoughtless, please do your research. It was very discouraging to be written to like this.

**Comment by Yzrsah** [comment]
Why do you think I write to you? Because you're one of the hardest working guys with dedication to css. I try to do some advanced stuff with css and of course I end up on your territories. Because you did a lot of work. That's not someone who is "very discouraged" by anything.

"I like you just the way you are"

You cannot do that without empathizing with every one.

You will have to think:
"Hmm. I like this Yzrsah just the way they are."
"Hmm, I like this Yzrsah who is quite mad about the `/`'s just the way they are"

"I wonder why they are so mad about those slashes? Since I like them just the way they are, now I am forced to wonder, and worry about them"
"Well, gee, now I must understand there could be a useful reality where their slashes have a different kind of importance."
"Maybe putting /'s in the middle of a color is actually pretty horrid?"
"What if we broke the color expressions on a basic level and now colors can't even be copy or pasted into any of one of 500 different softwares?"
"What if this guy is going nuts on the math expressions in the colors, and then we have a stupid slash in the middle of the color which is confusing and going in a bad direction?"

Sometimes there's so many issues that you don't get to sit back and enjoy the code.
I have to deal with a lot of issues that are coming up, and when I see this:
rgb(100% 50% 0% / 100%)
I think "aw, damn, now we gotta deal with this"

Add design guideline: "Don't try to use it with other stuff. Only use it in the code with the plugin." or "Don't write colors in this format"

What is the guideline?

**Comment by Yzrsah** [comment]
Why do you think I write to you? Because you're one of the hardest working guys with dedication to css. I try to do some advanced stuff with css and of course I end up on your territories. Because you did a lot of work. That's not someone who is "very discouraged" by anything.

"I like you just the way you are"

You cannot do that without empathizing with every one.

You will have to think:
"Hmm. I like this Yzrsah just the way they are."
"Hmm, I like this Yzrsah who is quite mad about the `/`'s just the way they are"

"I wonder why they are so mad about those slashes? Since I like them just the way they are, now I am forced to wonder, and worry about them"
"Well, gee, now I must understand there could be a useful reality where their slashes have a different kind of importance."
"Maybe putting /'s in the middle of a color is actually pretty horrid?"
"What if we broke the color expressions on a basic level and now colors can't even be copy or pasted into any of one of 500 different softwares?"
"What if this guy is going nuts on the math expressions in the colors, and then we have a stupid slash in the middle of the color which is confusing and going in a bad direction?"

Sometimes there's so many issues that you don't get to sit back and enjoy the code.
I have to deal with a lot of issues that are coming up, and when I see this:
rgb(100% 50% 0% / 100%)
I think "aw, damn, now we gotta deal with this"

Add design guideline: "Don't try to use it with other stuff. Only use it in the code with the plugin." or "Don't write colors in this format" What's the guideline?

**Comment by Yzrsah** [comment]
Why do you think I write to you? Because you're one of the hardest working guys with dedication to css. I try to do some advanced stuff with css and of course I end up on your territories. Because you did a lot of work. That's not someone who is "very discouraged" by anything.

"I like you just the way you are"

You cannot do that without empathizing with every one.

You will have to think:
"Hmm. I like this Yzrsah just the way they are."
"Hmm, I like this Yzrsah who is quite mad about the `/`'s just the way they are"

"I wonder why they are so mad about those slashes? Since I like them just the way they are, now I am forced to wonder, and worry about them"
"Well, gee, now I must understand there could be a useful reality where their slashes have a different kind of importance."
"Maybe putting /'s in the middle of a color is actually pretty horrid?"
"What if we broke the color expressions on a basic level and now colors can't even be copy or pasted into any of one of 500 different softwares?"
"What if this guy is going nuts on the math expressions in the colors, and then we have a stupid slash in the middle of the color which is confusing and going in a bad direction?"

Sometimes there's so many issues that you don't get to sit back and enjoy the code.
I have to deal with a lot of issues that are coming up, and when I see this:
`rgb(100% 50% 0% / 100%)`
I think "aw, damn, now we gotta deal with this"

Add design guideline: "Don't try to use it with other stuff. Only use it in the code with the plugin." or "Don't write colors in this format" What's the guideline?
