### ISSUE TITLE
Stripping "auto"

### ISSUE THREAD

**Issue by kezzbracey** [jonathantneal/postcss-short#4]
Hey Jonathan,

I'm having trouble at the moment using postcss-short as it seems to strip "auto" from values.

Using node v0.12.7 and PostCSS 4.1.16

I tried a short test directly via Node to try and rule out conflicts:

```
css = ".test { margin: 0 auto; }"

postcss(require('postcss-short')).process(css).then(function (result) {

  result.warnings().forEach(function (warn) {
    console.warn(warn.toString());
  });

  console.log(result.css)

});
```

This outputs:

```
.test { margin: 0; }
```

Has anyone else experienced this?

Thanks!

**Comment by jonathantneal** [comment]
This appears to be working in the latest version just fine. [[demo]](http://jonathantneal.github.io/postcss-short/#.test+%7B+margin:+0+auto;+%7D)
