### ISSUE TITLE
"*" results in error with Sass-Files

### ISSUE THREAD

**Issue by DotCoyote** [jonathantneal/postcss-short#6]
I'm using our Plugin with Gulp and Sass:

``` javascript

gulp.task 'styles', ->

  if compileOnly != false
    srcFile = compileOnly
  else
    srcFile = paths.files.sass

  processors = [
    postcssshort()
  ]

  gulp.src([ srcFile ], base: paths.folders.sass)
    .pipe( plumber({ errorHandler: notify.onError("Error: <%= error.message %>") }))
    .pipe(sourcemaps.init())
    .pipe(sass(
      sourcemap: true
    ))
    .pipe(postcss(processors))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(paths.folders.css))
    .pipe(browserSync.reload(stream: true))
    .pipe notify(
      message: 'Styles task complete'
      title: 'Styles'
      onLast: true)
```

``` sass
div
  margin: * auto
  position: absolute 50% *
```

results in the following error-message:

> gulp-notify: [Error running Gulp] Error: src/sass/_components/_base.sass
> Error: error reading values after on line 33 of src/sass/_components/_base.sass
>    margin: \* auto;
>   ---------^

**Comment by jonathantneal** [comment]
Unfortunately, this is one of a few parsing issues I’ve run into with the .sass and .scss syntaxes. They also choke on [Media Queries Level 4](https://drafts.csswg.org/mediaqueries/).

``` css
@media (width <= 1200px) {
  div {
    color: red;
  }
}
```

To be clear, these are bugs in Sass, part of their aggressive interpretation of math and media queries. I would [open an issue](https://github.com/sass/sass/issues) there.

**Comment by christianmagill** [comment]
@jonathantneal Could an alternate syntax, such as using "null" be added?

**Comment by mrcsmcln** [comment]
+1. I think that in the interest of maximum compatibility, `null` is a suitable alternative for preprocessors such as Sass.

**Comment by jonathantneal** [comment]
You may change the skip token ([documentation](https://github.com/jonathantneal/postcss-short-spacing#skip)). The default skip token will remain `*`. Alternatively, run PostCSS before you run Sass.

I sincerely hope they ditch all this magic math in the next major release.

**Comment by aleclarson** [comment]
I've taken the initiative to file an issue regarding the lack of interoperability [here](https://github.com/sass/sass/issues/2433).

Also the best workaround seems to be changing the skip token to `_`. 🙂

Side question: Does `postcss-short` support the `skip` option, or do I need to add `postcss-short-spacing` explicitly?
