### ISSUE TITLE
Config to indicate skipped token

### ISSUE THREAD

**Issue by maraisr** [jonathantneal/postcss-short#8]
I've been using [postcss-position](https://github.com/seaneking/postcss-position) (after having had a `@include position()` approach, and various `@include size(48px)` sass mixins for quite some time now to give me this "shorthand" approach. 

I used `false` as my token to indicate to skip the clockwise step. Now you're using `*`, is there someway I could set a config to use both `*` and `false` as I slowly phase out the `false`, so I can find-replace the `@include X`? Or just write some funky regex to replace the falses after the `@include X`, if there aren't enough consensus for this mod?

(I'd also be happy to make the mod as PR, if you're tight for time)

> Love the module mate, elegantly executed, clean API and modular!

**Comment by jonathantneal** [comment]
I’ve updated every single postcss short plugin to allow you to change the skip token like so: `{ skip: "*" }`.

**Comment by maraisr** [comment]
Thank you so much @jonathantneal
