### ISSUE TITLE
postcss-short-font-size dependency update

### ISSUE THREAD

**Issue by oleksiibilous** [jonathantneal/postcss-short#9]
Hello and thank you for your great work. I'm wondering if you are going to update `postcss-short-font-size` dependency to `v2`. I believe that second version has better syntax and it will be great to use it with `postcss-short` pack

**Comment by jonathantneal** [comment]
Done! https://github.com/jonathantneal/postcss-short/blob/master/CHANGELOG.md#200-2016-10-03
